version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    build:
      context: .
      dockerfile: Dockerfile-api
    command: celery -A vehicles worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile-api
    command: celery -A vehicles beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
